### ISSUE TITLE
XSS issue for user generated content

### ISSUE THREAD

**Issue by jeberly** [justin-schroeder/arrow-js#18]
First off, thanks for making this toolkit, it is a breath of fresh air. The description of project scope immediately appealed to me. I wish the project well. 

Related to https://github.com/justin-schroeder/arrow-js/issues/8  Any type of user generated data can contain XSS vulnerabilities. Using a sample from https://cheatsheetseries.owasp.org/cheatsheets/XSS_Filter_Evasion_Cheat_Sheet.html `<IMG SRC=/ onerror="alert(String.fromCharCode(88,83,83))"></img>` 

Which gives you: ![](https://clips-tmp-chatlio.s3.us-west-2.amazonaws.com/nAtLhGadj3l1H6qH-PcQW5FHnxOkWA52.png)

I think you should put a warning at minimum on the docs/readme until all known XSS issues are resolved. Thanks again for the project and its inspiring scope.

**Comment by justin-schroeder** [comment]
Yeah this is a bug that needs to get fixed. Its actually a regression from a previous private version. But definitely on the short list of things to get fixed

**Comment by justin-schroeder** [comment]
This should be fixed now in Alpha 2
