### ISSUE TITLE
w: not printing all outputs?

### ISSUE THREAD

**Issue by milkoqq** [justin-schroeder/arrow-js#19]
Hey, awesome work! Excuse my ignorance, I am a newbie with frameworks, proxies etc..! I've got a couple of questions.. 
1) Why doesn't the watcher log all the values in example below and just logs the first and the last one? I thought it would do something like $on/$off but with just a one-liner.. 
2) Since the watcher watches, why log immediately the function (for 25*10) since the data hasn't changed?
3) From the docs, I couldn't understand the use of $off in the example! Thanks!! Great work! 

```
const data = r({
  price: 25,
  quantity: 10,
  logTotal: true
})

function total () {
  if (data.logTotal) {
    console.log(`Total: ${data.price * data.quantity}`);
  }
}

w(total)

data.price = 35
data.price = 66
data.price = 150
```

**Comment by kyfex-uwu** [comment]
For 2, generally you'd want a "starting state". In this case it would be helpful to know the total at the start of the script.

**Comment by kyfex-uwu** [comment]
And .$off is scheduled to be put in the documentation, see #13

**Comment by justin-schroeder** [comment]
Watchers in arrow will always run eagerly, otherwise they don’t know what their dependencies are. You can provide a second argument which is a second callback that receives the result of the watcher, and then you can choose to do something else with that value.

**Comment by milkoqq** [comment]
Thanks a lot! Will try out, I think I got it!
