### ISSUE TITLE
Can arrow js be used along with a react component / function?

### ISSUE THREAD

**Issue by JohnVersus** [justin-schroeder/arrow-js#21]
I see great possibilities with arrow-js. Just curious if anyone has tested using arrow-js existing js frameworks like react.

**Comment by justin-schroeder** [comment]
Yes, no reason you couldn’t do this, but also no reason I would recommend doing this. If you are already using react, perhaps continuing that pattern in your code base would be advisable. That said, the goal here is to be a relatively guilt free drop in wherever it makes sense, so…have at it!
