### ISSUE TITLE
Click handlers not working anymore

### ISSUE THREAD

**Issue by nbgraham** [justin-schroeder/arrow-js#25]
I think `1.0.0-alpha.2` broke the click handlers. This code worked with `1.0.0-alpha.1`

Now

```js
import { t } from "@arrow-js/core";

t`
    <button @click=${() => console.log('click')}>Click</button>
`(document.getElementById('app'));
```

renders as
```html
<button @click="<!--➳❍--">&gt;Click</button>
```

<img width="83" alt="image" src="https://user-images.githubusercontent.com/11163850/203659446-e096982e-8f8a-4a3d-b198-cdb953c62a6d.png">

And clicking it does nothing

**Comment by nbgraham** [comment]
```js
t`
    <button @click=${() => console.log('click')} id="test">Click</button>
`(document.getElementById('app'));
```

renders as
```html
<button @click="<!--➳❍--"> id="test"&gt;Click</button>
```

<img width="135" alt="image" src="https://user-images.githubusercontent.com/11163850/203660083-11c27db1-6367-43b3-8282-66338060f406.png">

**Comment by justin-schroeder** [comment]
Well that's no good. I wonder why it's not broken in other instances. Will look into this more

**Comment by justin-schroeder** [comment]
Oh, I believe you need quotes around your callback yes?

**Comment by nbgraham** [comment]
oops, yes

but it did work without quotes in the old version, interesting
