### ISSUE TITLE
Allow arbitrary access to HTML element IDL attributes

### ISSUE THREAD

**Issue by atellmer** [justin-schroeder/arrow-js#33]
If I try to make a reactive style value, then the value of the CSS property in the style attribute is overwritten.

![1](https://user-images.githubusercontent.com/16635118/204882145-9d1b47fc-4bf5-4e2a-9293-c6a3f3d2c0d1.PNG)

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>arrow-js</title>
</head>
<body>
  <div id="app"></div>
  <script type='module'>
    import { reactive, html } from 'https://unpkg.com/@arrow-js/core@1.0.0-alpha.5/dist/index.min.mjs';

    const state = reactive({
      color: 'red'
    });

    html`
      <button style="background-color: ${() => state.color}">click me</button>
    `(document.getElementById('app'))
  </script>
</body>
</html>
```

**Comment by justin-schroeder** [comment]
reactive values cannot be applied to HTML partials only to entire attributes.

**Comment by justin-schroeder** [comment]
Perhaps it would be nice to support style objects:

```
const data = r({
  style: {
    backgroundColor: 'red'
  }
})
<button style="${() => state.style}">click me</button>
```

**Comment by atellmer** [comment]
Thanks. I realized that I can do this and it will work.

```javascript
import { reactive, html } from 'https://unpkg.com/@arrow-js/core@1.0.0-alpha.5/dist/index.min.mjs';

const state = reactive({
  backgroudColor: 'red',
  color: 'yellow'
});

const handleClick = () => {
  state.backgroudColor === 'red' ? (state.backgroudColor = 'yellow') : (state.backgroudColor = 'red');
  state.color === 'red' ? (state.color = 'yellow') : (state.color = 'red');
}

html`
  <button
    style="${() => `background-color: ${state.backgroudColor}; color: ${state.color};`}"
    @click="${handleClick}">
    toggle style
  </button>
`(document.getElementById('app'))
```

**Comment by rallu** [comment]
Would be nice to have for any attribute. I have web components that have array, object or function type of attributes. 

For example if we have a web component that would render dropdown based on options attribute that had array of values in dropdown. 

```
html`<my-dropdown options="${['one', 'two', 'three']}"></my-dropdown>`
```

**Comment by justin-schroeder** [comment]
@rallu since HTML can only have strings as attributes — would you expect this to perform some kind of `JSON.stringify()` and then you would decode that in your web component?

**Comment by rallu** [comment]
It's true that HTML supports only strings as attributes, but DOM HTMLElement supports any type of attributes.

I was hoping I could set these attributes easily with arrow. Now I have to get reference to element and set the attribute value with JS

JSON stringify is just bad design. Not going to use that.

Lit has solved this by having dot notation in templates. https://lit.dev/docs/templates/expressions/#property-expressions

**Comment by justin-schroeder** [comment]
I see what you're asking for. Not specifically a style object support but easier access to any arbitrary IDL attribute. I think I like the `.` prefix idea — this seems doable.

**Comment by justin-schroeder** [comment]
Ok, this has been implemented in alpha.7, you can now use a dot-prefix to pass internal properties to elements 👍
