### ISSUE TITLE
Syntax Highlighting for HTML template literals

### ISSUE THREAD

**Issue by eScribMac** [justin-schroeder/arrow-js#42]
Is it possible to enable syntax highlighting for html inside template literals in any popular editor? (VS Code, Webstorm, etc) Are there instructions on how to do so anywhere? Apologies if this is documented somewhere, I couldn't find it

**Comment by Bellisario** [comment]
Yes, there is a "preview" extension by @jhechtf, you can find it here: https://github.com/jhechtf/vscode-arrow-js

Anyway, if you already know Lit, you can use its extension, which seems to work pretty well (@justin-schroeder comment on https://github.com/justin-schroeder/arrow-js/discussions/23#discussioncomment-4227683)

---

P.S.: all this is referred to discussion #23.

**Comment by justin-schroeder** [comment]
We should add this to the docs!

**Comment by justin-schroeder** [comment]
Ok I added a little blurb to the docs. If @jhechtf decides to publish that project we'll include it on there too!

**Comment by jhechtf** [comment]
I mean I can go ahead and publish it but as it currently sits there's nothing particularly different about the arrow js extension vs the lit extension. Reply on the thread if you'd like to see that extension published.
