### ISSUE TITLE
fails to render with multiple expressions in an attribute

### ISSUE THREAD

**Issue by jukart** [justin-schroeder/arrow-js#64]
Here is a test which shows the problem:
```typescript
import { html } from '..'

describe('extressions in attribute', () => {
  it('should render correctly with a single expression in an attribute', () => {
    const parent = document.createElement('div')
    html`<div class="${() => 'class'}" @click="${() => 'click'}">
      ${() => 'body'}
    </div>`(parent)
    expect(parent.innerHTML).toStrictEqual(`<div class="class">
      body
    </div>`)
  })

  it('should render correctly with multiple expressions in an attribute', () => {
    const parent = document.createElement('div')
    html`<div class="${() => 'class1'} ${() => 'class2'}">
      ${() => 'body'}
    </div>`(parent)
    expect(parent.innerHTML).toStrictEqual(
      `<div class="<!--➳❍--> <!--➳❍-->">
      class1
    </div>`
    )
  })
})
```

**Comment by justin-schroeder** [comment]
This is intentional. You can only provide 1 expression for your attribute. This allows arrow to be small, fast and efficient, and still gives you plenty of ability to do what you’re asking.

```js
html`<div class="${() => 'class1'} ${() => 'class2'}"></div>
```

should be written:

```js
html`<div class="${() => `${d.class1} ${d.class2}`"></div>
```

**Comment by jukart** [comment]
Ok thanks for the quick reply. I was bringing this up because it worked before.
It broke some things in my app :)
But that`s why it's alpha :)

**Comment by jukart** [comment]
@justin-schroeder 
Another note:
This also fails:
`width="${width}px"`
It has to be this:
```width="${`${width}px`}"```

I'd say this should be mentioned somewhere in the documentation because strange things are happening if you do it wrong.
