### ISSUE TITLE
Distinguish text content from HTML content

### ISSUE THREAD

**Issue by jaredkrinke** [justin-schroeder/arrow-js#8]
In templates, is there any way to distinguish plain text content from HTML content? Or does the caller need to always escape arbitrary text values?

As a contrived example, in [the docs](https://www.arrow-js.com/#templates) under the "Event" header, if I type `<b>bold!` into the text box, bold text appears, so it seems I can insert arbitrary HTML. That's fine for hard-coded values, but seems like a security issue for anything derived from user input.

For what it's worth, I like the minimal, modern JS-based approach of ArrowJS, but this seems like a potential footgun :)

**Comment by justin-schroeder** [comment]
Yeah, this 100% isn't supposed to happen. should be doing an `innerText` assignment for some reason it isnt, but that should be fairly easy to get fixed I think.
