### ISSUE TITLE
Dark mode flashbang 🫣

### ISSUE THREAD

**Issue by PickleNik** [justin-schroeder/arrow-js#80]
there's a split-second light mode flash before the dark mode is applied when visiting the https://www.arrow-js.com/ and also when navigating to Docs

one possible solution could be to set html's `background-color` property based on `@media(prefers-color-scheme: dark)` in CSS by default and then let JS take over the theming

**Comment by justin-schroeder** [comment]
Thats true, happy to accept a PR for that if you’d like to do it 👍
